title: Justas Gasparaitis
email: gasparaitisjustas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Articles, posts & more.
baseurl: ""
logo: "/images/profile.png" # path of site logo, e.g. "/assets/images/logo.png"
locale: "en-us"

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: gasparaitisj # site's Twitter username

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
#defaults:
#  # Post defaults
#  - scope:
#      path: "_posts"
#      type: posts
#    values:
#      layout: post
#      comments: true
#      share: true
#  # Recipe defaults
#  - scope:
#      path: "_recipes"
#      type: recipes
#    values:
#      layout: post
#      comments: true
#      share: true

excerpt_separator: <!--end_excerpt-->

# Site Author
author:
  name: Justas Gasparaitis
  picture: /images/profile.png
  email: gasparaitisjustas@gmail.com
  twitter: gasparaitisj
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/gasparaitisj/
      icon: fab fa-linkedin-in
    - title: GitHub
      url: https://github.com/gasparaitisj
      icon: fab fa-github
    - title: Medium
      url: https://medium.com/@gasparaitisj
      icon: fab fa-medium-m

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/gasparaitisj/
    icon: fab fa-linkedin-in
  - title: GitHub
    url: https://github.com/gasparaitisj
    icon: fab fa-github
  - title: Medium
    url: https://medium.com/@gasparaitisj
    icon: fab fa-medium-m
